services:
  - type: web
    name: abandoned-arcade
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require

